### ISSUE TITLE
fails to compile

### ISSUE THREAD

**Issue by MasterSwift** [bkostjens/Perfect-Turnstile-MongoKittenDB#1]
this should compile but it doesnt for some strange reason. using mongokitten 4

error: argument passed to call that takes no arguments
tokenStore = AccessTokenStore(server: connect)
                             ~~~~~~~~~^~~~~~~~
error: incorrect argument label in call (have 'server:', expected 'sessionManager:')
let pturnstile = TurnstilePerfectRealm(server: connect)

**Comment by bkostjens** [comment]
Correct, MongoKitten 4 isn't supported.
